# Generated by Django 5.0.2 on 2024-02-25 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('PostID', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=30)),
                ('BodyText', models.TextField()),
                ('Field', models.CharField(max_length=15)),
                ('DatePosted', models.DateField()),
                ('Link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('PhoneNumber', models.CharField(max_length=10)),
                ('PasswordHash', models.CharField(max_length=127)),
                ('DOB', models.DateField()),
                ('AboutMe', models.TextField()),
                ('Email', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careercompassapp.posts')),
            ],
        ),
        migrations.CreateModel(
            name='Recruiters',
            fields=[
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='careercompassapp.users')),
                ('CompanyName', models.CharField(max_length=20)),
                ('AboutCompany', models.TextField()),
                ('Position', models.CharField(max_length=20)),
                ('CompanyLink', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='careercompassapp.users')),
                ('University', models.CharField(max_length=60)),
                ('Degree', models.CharField(max_length=48)),
                ('CurrentYear', models.CharField(max_length=9)),
                ('ExpectedGraduation', models.DateField()),
                ('GPA', models.DecimalField(decimal_places=1, max_digits=1)),
                ('OpenToWork', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddConstraint(
            model_name='users',
            constraint=models.CheckConstraint(check=models.Q(('PhoneNumber__regex', '^[0-9]{10}$')), name='valid_phone_number'),
        ),
        migrations.AddConstraint(
            model_name='users',
            constraint=models.UniqueConstraint(fields=('Email',), name='unique_email'),
        ),
        migrations.AddField(
            model_name='posts',
            name='PostedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careercompassapp.users'),
        ),
        migrations.AddField(
            model_name='likes',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careercompassapp.users'),
        ),
        migrations.AddField(
            model_name='followers',
            name='FollowerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_as_follower', to='careercompassapp.users'),
        ),
        migrations.AddField(
            model_name='followers',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_as_user', to='careercompassapp.users'),
        ),
        migrations.AddConstraint(
            model_name='likes',
            constraint=models.UniqueConstraint(fields=('UserID', 'PostID'), name='unique_like_combination'),
        ),
        migrations.AddConstraint(
            model_name='followers',
            constraint=models.UniqueConstraint(fields=('UserID', 'FollowerID'), name='unique_follower_combination'),
        ),
    ]
