# Generated by Django 5.0.2 on 2024-02-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.CharField(max_length=15)),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('PhoneNumber', models.CharField(max_length=10)),
                ('PasswordHash', models.CharField(max_length=127)),
                ('DOB', models.DateField()),
                ('AboutMe', models.TextField()),
                ('Email', models.CharField(max_length=63)),
            ],
        ),
        migrations.AddConstraint(
            model_name='users',
            constraint=models.CheckConstraint(check=models.Q(('PhoneNumber__regex', '^[0-9]{10}$')), name='valid_phone_number'),
        ),
        migrations.AddConstraint(
            model_name='users',
            constraint=models.UniqueConstraint(fields=('Email',), name='unique_email'),
        ),
        migrations.AddConstraint(
            model_name='users',
            constraint=models.CheckConstraint(check=models.Q(('UserID__regex', '^.{15}$')), name='min_length_userID'),
        ),
    ]
