# Generated by Django 5.0.2 on 2024-02-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careercompassdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AlterField(
            model_name='users',
            name='UserID',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
